[build]
  command = "npm run build"
  functions = ".netlify/functions/"

[context.production.environment]
  WHO_AM_I = "World"

[context.deploy-preview]
  command = "WHO_AM_I=DeployPreview npm run build"

[context.deploy-preview.environment]
  WHO_AM_I = "Developer"
